### ISSUE TITLE
Comparisons Between DBs

### ISSUE THREAD

**Issue by dm03514** [dm03514/db-insights#8]
- Don't create an abstraction over SQL just help to execute sql across multiple backends
- Comparisions takes the configured dbs and executes SQL against all of them and returns a comparison result

Comparisons must have:
- At least one additional db (contained in `dbs:`) 
- A valid `type` of additional `db`
- A valid connection string 
- A single integer (count) returned from each SQL statement 

```
# comparisons.yml

comparisons:
  dbs:
    - name: redshift
    type: redshift
    connection_string_env_var: CONNECTION_STRING
  targets:
    - name: test
    sql_statements:
      - db: primary
      name: "some_sql_resource"
      sql: "SELECT * FROM ___"
      - db: redshift
      name: "some_sql_resource"
      sql: "SELECT * FROM ___" 
```
